name = "indocp"
uuid = "748cb5ea-2809-4e34-b5b2-c885eed8e4c4"
authors = ["Jeremy Rouot"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
